Exception in thread ""main"" java.lang.Exception: Unsatisfied expectation:

Expected:
inAnyOrder {
  <mock-1> Cat.meow() once (never called - UNSATISFIED)
  <mock-1> Cat.isHungry() any number of times (called once)
}

Actual:
  <mock-1> Cat.isHungry(), None
    at NoScalaTestExample$MyMockFactoryBase.newExpectationException(NoScalaTestExample.scala:13)
    at NoScalaTestExample$MyMockFactoryBase.newExpectationException(NoScalaTestExample.scala:10)
    at org.scalamock.context.MockContext$class.reportUnsatisfiedExpectation(MockContext.scala:45)
    at NoScalaTestExample$MyMockFactoryBase.reportUnsatisfiedExpectation(NoScalaTestExample.scala:10)
