val (e, f): (Int, Int) = Try {
  myfunction("4")
} match {
  case Success((x, y)) => (x, y)
  case Failure(ex: NumberFormatException) =>
    throw new NumberFormatException(s"Exception caught: ${ex.getMessage}")
  case Failure(ex) =>
    throw new Exception(s"Unexpected exception: ${ex.getMessage}")
}
// e: Int = 4
// f: Int = 8

val (g, h): (Int, Int) = Try {
  myfunction("string")
} match {
  case Success((x, y)) => (x, y)
  case Failure(ex: NumberFormatException) =>
    throw new NumberFormatException(s"Exception caught: ${ex.getMessage}")
  case Failure(ex) =>
    throw new Exception(s"Unexpected exception: ${ex.getMessage}")
}
// java.lang.NumberFormatException: Exception caught: For input string: "string"
