directly: [ Error: timeout
    at Promise (...\scratch_2.es6:6:30)
    at new Promise (<anonymous>)
    at someHandler (...\scratch_2.es6:5:29)
    at Object.<anonymous> (...\scratch_2.es6:20:2)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10) ]
in _write: [ Error: timeout
    at Promise (...\scratch_2.es6:6:30)
    at new Promise (<anonymous>)
    at someHandler (...\scratch_2.es6:5:29)
    at Writable.write [as _write] (...\scratch_2.es6:29:4)
    at doWrite (_stream_writable.js:397:12)
    at writeOrBuffer (_stream_writable.js:383:5)
    at Writable.write (_stream_writable.js:290:11)
    at Object.<anonymous> (...\scratch_2.es6:36:9)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10) ]
(node:3288) UnhandledPromiseRejectionWarning: Error: timeout
    at Promise (...\scratch_2.es6:6:30)
    at new Promise (<anonymous>)
    at someHandler (...\scratch_2.es6:5:29)
    at Writable.write [as _write] (...\scratch_2.es6:29:4)
    at doWrite (_stream_writable.js:397:12)
    at writeOrBuffer (_stream_writable.js:383:5)
    at Writable.write (_stream_writable.js:290:11)
    at Object.<anonymous> (...\scratch_2.es6:36:9)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
(node:3288) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3288) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
